# File Summary:

This file performs EDA on the data from Reddit using the pushshift api, see notebook 3a.

In this file, I combined the files created in notebook 3a.  To account for the overlapping information in each fild, I looked up the timestamp of the last entry for each file.  I then found in which entry that timestamp appears in the next file, and used the index of it when concatenating all the files so that duplicates did not occur.

Note that I checked how often multiple entries have the same timestamp.  I found 20 entries with duplicate timestamps out of 16000 entries in the first file.  So I didn't worry about the risk that the last entry in one file, would not be the same entry as the first time that the timestamp of that last entry appears in the next file.

After combining the entire republican and entire democrat data and removing duplicates, I then selected key features that I found were similar in both.  I based these features on ones that I used in the analysis on the data downloaded using the PRAW api, as well as features that appeared to generally have information.  

Finally, I filtered the both republican and democrat datasets so that I only had the key features in the two dataframes, and I combined these into one and saved it (reps_and_dems.csv) for further analysis in other notebooks.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# display all columns
# from https://towardsdatascience.com/how-to-show-all-columns-rows-of-a-pandas-dataframe-c49d4507fcf

pd.set_option('display.max_columns', None)

In [3]:
dems1 = pd.read_csv('../data/dems.csv')
dems2 = pd.read_csv('../data/dems2.csv')
dems3 = pd.read_csv('../data/dems3.csv')
dems4 = pd.read_csv('../data/dems4.csv')
dems5 = pd.read_csv('../data/dems5.csv')
dems6 = pd.read_csv('../data/dems6.csv')
dems7 = pd.read_csv('../data/dems7.csv')

/Users/jenniferwilliamson/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (8,9,25,41,57,60,63,70,71,74,75,76,77,78,79,82,83,84,86,87) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/Users/jenniferwilliamson/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (1,3,5,9,49,73) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/Users/jenniferwilliamson/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (1,2,3,4,5,6,7,8,12,14,15,16,17,18,20,22,23,25,26,28,29,33,35,40,41,46,50,60,61,62,64,68,69,70,71,73,75,76,77,78,79,80,81,82) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_

In [4]:
reps1 = pd.read_csv('../data/reps.csv')
reps2 = pd.read_csv('../data/reps2.csv')
reps3 = pd.read_csv('../data/reps3.csv')
reps4 = pd.read_csv('../data/reps4.csv')
reps5 = pd.read_csv('../data/reps5.csv')
reps6 = pd.read_csv('../data/reps6.csv')
reps7 = pd.read_csv('../data/reps7.csv')

C:\Users\jennw\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (3,8,9,51,57,60,65,73,74,75,77,79,82,83,84,86,87) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\jennw\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (1,9,43) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\jennw\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (2,4,6,7,8,12,14,15,16,17,18,20,22,23,24,28,29,33,35,44,45,50,56,59,60,62,63,64,67,69,72,73,75,76,78,79,80,81,82,84,86,88,89,90,91,92) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [5]:
dems1.head()

all_awardings  allow_live_comments              author  \
0            []                False           SP4C3B4S3   
1            []                False  Singularitytracker   
2            []                False     1000000students   
3            []                False          hornet7777   
4            []                False   GodverdommeCoffee   

  author_flair_css_class author_flair_richtext author_flair_text  \
0                    NaN                    []               NaN   
1                    NaN                    []               NaN   
2                    NaN                    []               NaN   
3                    NaN                    []               NaN   
4                    NaN                    []               NaN   

  author_flair_type author_fullname author_patreon_flair author_premium  \
0              text     t2_75st1vsp                False          False   
1              text     t2_5ny3j53h                False          False   
2              text        t2_7vedo                False          False   
3              text        t2_z3ajl                False          False   
4              text        t2_84twh                False          False   

  awarders  can_mod_post  contest_mode  created_utc                   domain  \
0       []         False         False   1602943707                i.redd.it   
1       []         False         False   1602945905                i.redd.it   
2       []         False         False   1602945922           self.democrats   
3       []         False         False   1602946014  borntorunthenumbers.com   
4       []         False         False   1602946028                 youtu.be   

                                           full_link gildings      id  \
0  https://www.reddit.com/r/democrats/comments/jc...       {}  jcvqal   
1  https://www.reddit.com/r/democrats/comments/jc...       {}  jcwcnk   
2  https://www.reddit.com/r/democrats/comments/jc...       {}  jcwctt   
3  https://www.reddit.com/r/democrats/comments/jc...       {}  jcwdt1   
4  https://www.reddit.com/r/democrats/comments/jc...       {}  jcwdy3   

   is_crosspostable  is_meta  is_original_content  is_reddit_media_domain  \
0             False    False                False                    True   
1             False    False                False                    True   
2             False    False                False                   False   
3             False    False                False                   False   
4             False    False                False                   False   

   is_robot_indexable  is_self  is_video link_flair_background_color  \
0               False    False     False                         NaN   
1               False    False     False                         NaN   
2               False     True     False                     #646d73   
3               False    False     False                         NaN   
4               False    False     False                     #b8001f   

                 link_flair_richtext link_flair_text_color link_flair_type  \
0                                 []                  dark            text   
1                                 []                  dark            text   
2  [{'e': 'text', 't': '📉 Economy'}]                 light        richtext   
3                                 []                  dark            text   
4    [{'e': 'text', 't': '📺 Video'}]                 light        richtext   

   locked  media_only  no_follow  num_comments  num_crossposts  over_18  \
0   False       False       True             2               0    False   
1   False       False       True             2               0    False   
2   False       False       True             0               0    False   
3   False       False       True             0               0    False   
4   False       False       True             0               0    False   

  parent_whitelist_status                    

In [6]:
reps1.head()

all_awardings  allow_live_comments          author author_flair_css_class  \
0            []                False          Foubar                    NaN   
1            []                False       Dan-In-SC                    NaN   
2            []                False          Foubar                    NaN   
3            []                False       Dan-In-SC                    NaN   
4            []                False  slimfatboy2005                    NaN   

  author_flair_richtext author_flair_text author_flair_type author_fullname  \
0                    []               NaN              text        t2_tpsej   
1                    []               NaN              text     t2_1o0d4hsp   
2                    []               NaN              text        t2_tpsej   
3                    []               NaN              text     t2_1o0d4hsp   
4                    []               NaN              text     t2_54fxtvjv   

  author_patreon_flair author_premium awarders  can_mod_post  contest_mode  \
0                False           True       []         False         False   
1                False           True       []         False         False   
2                False           True       []         False         False   
3                False           True       []         False         False   
4                False          False       []         False         False   

   created_utc                  domain  \
0   1602943321  washingtonexaminer.com   
1   1602943857        toptradeguru.com   
2   1602943877              hotair.com   
3   1602944546              nypost.com   
4   1602945764               i.redd.it   

                                           full_link gildings      id  \
0  https://www.reddit.com/r/Republican/comments/j...       {}  jcvmgy   
1  https://www.reddit.com/r/Republican/comments/j...       {}  jcvrrg   
2  https://www.reddit.com/r/Republican/comments/j...       {}  jcvryj   
3  https://www.reddit.com/r/Republican/comments/j...       {}  jcvymk   
4  https://www.reddit.com/r/Republican/comments/j...       {}  jcwb5s   

   is_crosspostable  is_meta  is_original_content  is_reddit_media_domain  \
0              True    False                False                   False   
1              True    False                False                   False   
2              True    False                False                   False   
3              True    False                False                   False   
4             False    False                False                    True   

   is_robot_indexable  is_self  is_video  link_flair_background_color  \
0                True    False     False                          NaN   
1                True    False     False                          NaN   
2                True    False     False                          NaN   
3                True    False     False                          NaN   
4               False    False     False                          NaN   

  link_flair_richtext link_flair_text_color link_flair_type  locked  \
0                  []                  dark            text   False   
1                  []                  dark            text   False   
2                  []                  dark            text   False   
3                  []                  dark            text   False   
4                  []                  dark            text   False   

   media_only  no_follow  num_comments  num_crossposts  over_18  \
0       False       True            33               0    False   
1       False       True             6               0    False   
2       False       True             2               0    False   
3       False       True            12               0    False   
4       False       True             6               0    False   

  parent_whitelist_status                                          permalink  \
0                 all_ads  /r/Republican/comments/jcvmgy/biden_says_he_wi...   

# Combine the 7 data frames that I downloaded 

## there's some overlap, so I found where the timestamp for the last entry of the previous dataframe starts on the next data frame, so that I can only have one entry for each.  There's a small chance this could result in multiple entries (I found 20 entries with duplicate times stamps out of 16000 earlier, so it's highly unlikely.

In [7]:
def list_starts(list_of_dfs):
    
    list_of_indices = []
  
    for i in range(len(list_of_dfs)-1):
        df1 = list_of_dfs[i]
        df2 = list_of_dfs[i+1]
        
        last_utc = df1['created_utc'].tail(1).iloc[0]
        
        start_new_index = df2['created_utc'][df2['created_utc'] == last_utc].index.values + 1 
        
        #start_new_index = start_new_index[0]
        
        #print(f'The last utc of the {i} dataframe is {last_utc}.')
        #print(f'So the start index of the {i+1} dataframe should be {start_new_index}.')
        
        list_of_indices.append(start_new_index)
        
    return list_of_indices


In [8]:
dems_list = [dems1, dems2, dems3, dems4, dems5, dems6, dems7]
reps_list = [reps1, reps2, reps3, reps4, reps5, reps6, reps7]

In [9]:
dl = list_starts(dems_list)
dl

[array([], dtype=int64),
 array([870], dtype=int64),
 array([833], dtype=int64),
 array([50], dtype=int64),
 array([123], dtype=int64),
 array([34], dtype=int64)]

In [10]:
rl = list_starts(reps_list)
rl

[array([], dtype=int64),
 array([351], dtype=int64),
 array([598], dtype=int64),
 array([55], dtype=int64),
 array([64], dtype=int64),
 array([196], dtype=int64)]

In [11]:
all_dems = pd.concat([dems1, dems2, dems3[dl[1][0]:], dems4[dl[2][0]:],dems5[dl[3][0]:],dems6[dl[4][0]:],dems7[dl[5][0]:]])
all_dems.shape

(123668, 99)

In [12]:
all_reps = pd.concat([reps1, reps2, reps3[rl[1][0]:], reps4[rl[2][0]:], reps5[rl[3][0]:], reps6[rl[4][0]:], reps7[rl[5][0]:]])
all_reps.shape

(90351, 107)

# Reduce dataframes to only features we're interested in

In [13]:
FEATURES = ['author','author_fullname','created_utc','domain','full_link','id','num_comments','permalink','score','subreddit','title','url']

all_dems_F = all_dems[FEATURES]
all_reps_F = all_reps[FEATURES]

In [14]:
all_dems_F.shape

(123668, 12)

In [15]:
all_reps_F.shape

(90351, 12)

In [16]:
all_dems_F.isnull().sum()

author                 0
author_fullname    24401
created_utc            0
domain                 0
full_link              0
id                     0
num_comments           0
permalink              0
score                  0
subreddit              0
title                  0
url                    0
dtype: int64

In [17]:
all_reps_F.isnull().sum()

author                 0
author_fullname    15423
created_utc            0
domain                 3
full_link              0
id                     0
num_comments           0
permalink              0
score                  0
subreddit              0
title                  0
url                    0
dtype: int64

In [18]:
all_F = pd.concat([all_dems_F,all_reps_F])

In [19]:
all_F.head()

author author_fullname  created_utc                   domain  \
0           SP4C3B4S3     t2_75st1vsp   1602943707                i.redd.it   
1  Singularitytracker     t2_5ny3j53h   1602945905                i.redd.it   
2     1000000students        t2_7vedo   1602945922           self.democrats   
3          hornet7777        t2_z3ajl   1602946014  borntorunthenumbers.com   
4   GodverdommeCoffee        t2_84twh   1602946028                 youtu.be   

                                           full_link      id  num_comments  \
0  https://www.reddit.com/r/democrats/comments/jc...  jcvqal             2   
1  https://www.reddit.com/r/democrats/comments/jc...  jcwcnk             2   
2  https://www.reddit.com/r/democrats/comments/jc...  jcwctt             0   
3  https://www.reddit.com/r/democrats/comments/jc...  jcwdt1             0   
4  https://www.reddit.com/r/democrats/comments/jc...  jcwdy3             0   

                                           permalink  score  subreddit  \
0      /r/democrats/comments/jcvqal/happy_halloween/      1  democrats   
1  /r/democrats/comments/jcwcnk/someone_i_follow_...      1  democrats   
2  /r/democrats/comments/jcwctt/how_donald_trump_...      1  democrats   
3  /r/democrats/comments/jcwdt1/btrtn_ten_days_in...      1  democrats   
4  /r/democrats/comments/jcwdy3/never_forget_that...      1  democrats   

                                               title  \
0                                   Happy Halloween!   
1  someone I follow pointed out that Russia today...   
2  HOW DONALD TRUMP AND THE REPUBLICAN PARTY SCRE...   
3  BTRTN: Ten Days in November... Would You Make ...   
4  Never forget that long after he's gone our chi...   

                                                 url  
0                https://i.redd.it/jo3xacq3xnt51.jpg  
1                https://i.redd.it/yg8h7i2j3ot51.png  
2  https://www.reddit.com/r/democrats/comments/jc...  
3  http://www.borntorunthenumbers.com/2020/10/btr...  
4                       https://youtu.be/TeOePoa4z-c

In [20]:
clean_FEATURES = ['created_utc','id','num_comments','score','subreddit','title','url']

all_clean = all_F[clean_FEATURES]

In [21]:
all_clean.to_csv('../data/reps_and_dems.csv', index=False)